config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "guides#index"

  resources :guides, only: %i[index create destroy show] do
    collection do
      get :index_two
      post :update_two
    end
    get :show_two

  end




  resources :programs, only: %i[show]
  
  resources :projects, only: %i[show] do
    collection do
      get :fetch_by_program
    end
  end

  resources :presentation, only: %i[show]
  resources :points, only: %i[show update] 
   
  



 

  resources :batches, only: %i[index show] do
    collection do
      post :import_students
      post :edit
      post :update
      post :create_two
      get :index_two
      get :assign_guides_manually
      post :assign_guides_manually_post
      get :change_teammate
      post :change_teammate_post
      
      # import students via excel
      post :preview_students
      get :preview_students_in_html
      post :confirm_students
      post :cancel_students
      
      # import guides via excel
      post :preview_guides
      get :preview_guides_in_html
      post :confirm_guides
      post :cancel_guides


    end
    get :show_two
  end

  resources :students, only: :show do
    collection do
      post :edit_student
      post :update_student
      post :update_guide
    end
  end
  
end

app/views/shared/_batches.html.erb
<% if @batches.present? %>
  <% @batches.each do |b| %>
    <!-- Card for each batch -->
    <div id="edit_batch<%= b.id %>" class="relative bg-white shadow-md rounded-lg border-t-4 border-purple-500 hover:shadow-lg transition-shadow duration-300 ease-in-out">
      <!-- Card Header -->
      <div class="flex justify-between items-center p-4">
        <!-- Batch Name -->
        <h3 class="text-lg font-semibold text-gray-800">
          <%= link_to b.name, batch_path(b), class: "hover:underline text-purple-600" %>
        </h3>

        <!-- Actions -->
        <% if session[:guide_id] %>
          <% if Guide.find(session[:guide_id]).type == "Coordinator" %>
            <div class="grid place-items-end">
              <%= link_to "Upload Guides", batch_show_two_path(b), class: "bg-emerald-600 text-white font-medium py-1 px-2 rounded-lg shadow-md hover:bg-emerald-500 focus:ring-4 focus:ring-emerald-400 transition:ease-in duration-300" %>
            </div>
          <% end %>

          <!-- Edit Icon -->
          <div>
            <%= button_to edit_batches_path(batch_id: b.id), data: { turbo_method: :post } do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-red-600 hover:text-red-500 transition duration-200">
                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
              </svg>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <!-- No batches found -->
  <div class="col-span-full text-center text-gray-500">
    <p>No batches available at the moment.</p>
  </div>
<% end %>

app/views/shared/_edit_batch.html.erb
<%= form_with(url: batches_path, method: :post, scope: :batch, class:"my-5 p-3") do |f| %>
  <%= f.text_field :name, value: Batch.find(params[:batch_id]).name, class: "text-purple-500" %>
  <%= f.hidden_field :id, value: params[:batch_id] %>
  <%= f.submit "Save", class: "bg-purple-500 px-2 py-1 mt-2 hover:bg-purple-400 transition:ease-in duration-300 rounded-md text-white" %>
<% end %>

app/views/shared/_sidebar.html.erb
<button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
   <span class="sr-only">Open sidebar</span>
   <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
   <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
   </svg>
</button>

<aside id="default-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
   <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
      <ul class="space-y-2 font-medium">
        <% guide = Guide.find(session[:guide_id] )%>

        <% unless guide.type == "Hod" %>
         <li>
            <%= link_to batches_path, class:"flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do %>

               <svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                  <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
                  <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
               </svg>
               <span class="ms-3">Dashboard</span>
            <% end %>

         </li>
         <% else %>

         <li>
            <%= link_to index_two_guides_path, class:"flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do %>
                <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                    <path d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"/>
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Users</span>
            <% end %>
         </li>

         <% end %>


         <li>
     
            <%= link_to guide_path(Guide.find(session[:guide_id])), data:{turbo_method: :delete, turbo_confirm: "Are you sure you want to Log Out?"}, class:"flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do %>
                <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 16">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"/>
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Log Out</span>
            <% end %>
         </li>
    
      </ul>
   </div>
</aside>

<div class="p-4 sm:ml-64">
  <% if Guide.find(session[:guide_id]).type == "Coordinator" %>
  <div class="grid place-itens-center">
    <span class="text-red-500 grid font-bold font-2xl">Logged In As Section <%= Guide.find(session[:guide_id]).section %> Coordinator</span>
  </div>
  <% end %>

  <% if notice %>
    <p class="bg-green-500 text-white p-3"><%= notice %></p>
  <% elsif alert %>
    <p class="bg-red-500 text-white p-3"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>